name: Daily Repository Update

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

permissions:
  contents: write   # 👈 THIS gives the bot permission to push commits

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # We'll use our own token

      - name: Configure Git and Commit (22f1001438@ds.study.iitm.ac.in)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "22f1001438@ds.study.iitm.ac.in"
          echo "Last updated on $(date -u)" > daily-update.txt
          git add daily-update.txt
          git commit -m "Daily automated update [skip ci]" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
